### PR TITLE
Prevent expired sessions from panicing

### LINKED ISSUE #17: Expired sessions cause a panic
We need to get some proper error handling and this is just one example of some missing error handling that is a blocker for moving forward.
```
ERROR liana_gui:633: panic occurred at line 45 of file lianad/src/payjoin/receiver.rs: Some("Failed to extract request: V2(SessionError(Expired(SystemTime { tv_sec: 1753496994, tv_nsec: 994737411 })))")
   0: liana_gui::setup_panic_hook::{{closure}}
```

### PR DESCRIPTION
**Pull request by benalleng**
Closes #17

This should prevent panics when getting expired sessions from the directory.

### CODE REVIEW

**Comment by benalleng** [comment]
Found another place where it panics I am going to try to address

**Review by arminsabouri — APPROVED** [review]

File: lianad/src/commands/mod.rs [hunk 1]
```diff
@@ -152,6 +153,9 @@ impl fmt::Display for CommandError {
             Self::FailedToPostOriginalPayjoinProposal(e) => {
                 write!(f, "Failed to post original payjoin proposal: '{}'.", e)
             }
+            Self::ReplayError(e) => {
+                write!(f, "Payjoin replay failed: '{}'.", e)
```
Comment (arminsabouri) [inline lianad/src/commands/mod.rs:157]: Nit:
```suggestion
                write!(f, "Payjoin session replay failed: '{}'.", e)
```

**Review by arminsabouri — APPROVED** [review]
ack
